AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal SAM template for ETL pipeline (fill in ARNs and bucket names)

Resources:
  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_ingest.handler
      Runtime: python3.11
      Timeout: 30
      Policies:
        - S3WritePolicy:
            BucketName: your-raw-bucket
      Environment:
        Variables:
          RAW_BUCKET: your-raw-bucket
          RAW_PREFIX: etl/raw/
          SOURCE_URL: https://jsonplaceholder.typicode.com/todos
